language: java
jdk:
  - openjdk11

# Git Push할 Branch
branches:
  only:
    - master

# gradlew 권한 추가.
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r toy *
  - mkdir -p deploy
  - mv toy.zip deploy/toy.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: my-toyproject-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: my-toyproject-springboot-build
    key: toy.zip
    bundle_type: zip
    application: my-toyproject
    deployment_group: my-toyproject-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - shmin11@naver.com